alter table public.bench_adoptions
  add column contribution_amount numeric(10, 2),
  add column payment_method text,
  add column is_anonymous boolean not null default false,
  add column receipt_number text;

update public.bench_adoptions
set contribution_amount = 3500,
    payment_method = 'check',
    receipt_number = 'VCP-POC-' || upper(substr(replace(id::text, '-', ''), 1, 8));

alter table public.bench_adoptions
  alter column contribution_amount set not null,
  alter column payment_method set not null,
  alter column receipt_number set not null,
  add constraint bench_adoptions_contribution_floor
    check (contribution_amount >= 3500 and contribution_amount <= 999999.99),
  add constraint bench_adoptions_payment_method
    check (payment_method in ('card', 'bank', 'zelle', 'check', 'stock', 'daf')),
  add constraint bench_adoptions_receipt_number_unique unique (receipt_number),
  add constraint bench_adoptions_supported_duration
    check (
      (duration_unit = 'month' and duration_count between 1 and 120)
      or (duration_unit = 'year' and duration_count between 1 and 10)
    );

drop policy "Adoptions are publicly readable" on public.bench_adoptions;
revoke select on public.bench_adoptions from anon, authenticated;

create table public.bench_updates (
  id bigint generated by default as identity primary key,
  bench_id text not null references public.benches(id) on delete cascade,
  changed_at timestamptz not null default now()
);

alter table public.bench_updates enable row level security;

create policy "Bench updates are publicly readable"
  on public.bench_updates for select
  to anon, authenticated
  using (true);

grant select on public.bench_updates to anon, authenticated;

create or replace function public.notify_bench_adoption()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.bench_updates (bench_id) values (new.bench_id);
  return new;
end;
$$;

create trigger notify_bench_adoption_insert
after insert on public.bench_adoptions
for each row execute function public.notify_bench_adoption();

create or replace function public.list_benches()
returns table (
  id text,
  name text,
  area text,
  latitude double precision,
  longitude double precision,
  source text,
  source_reference text,
  adopter_name text,
  plaque_message text,
  adoption_start date,
  adoption_end date,
  hold_expires_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    bench.id,
    bench.name,
    bench.area,
    bench.latitude,
    bench.longitude,
    bench.source,
    bench.source_reference,
    case
      when current_adoption.is_anonymous then 'Anonymous patron'::text
      else current_adoption.adopter_name
    end,
    current_adoption.plaque_message,
    current_adoption.adoption_start,
    current_adoption.adoption_end,
    active_hold.expires_at
  from public.benches as bench
  left join lateral (
    select adoption.adopter_name,
      adoption.plaque_message,
      adoption.adoption_start,
      adoption.adoption_end,
      adoption.is_anonymous
    from public.bench_adoptions as adoption
    where adoption.bench_id = bench.id
      and current_date between adoption.adoption_start and adoption.adoption_end
    order by adoption.adoption_end desc
    limit 1
  ) as current_adoption on true
  left join lateral (
    select hold.expires_at
    from public.bench_adoption_holds as hold
    where hold.bench_id = bench.id
      and hold.expires_at > now()
    limit 1
  ) as active_hold on true
  order by bench.id;
$$;

drop function public.adopt_bench(text, uuid, text, text, integer, text);

create function public.adopt_bench(
  p_bench_id text,
  p_session_token uuid,
  p_adopter_name text,
  p_plaque_message text,
  p_duration_count integer,
  p_duration_unit text,
  p_contribution_amount numeric,
  p_payment_method text,
  p_is_anonymous boolean
)
returns table (
  success boolean,
  message text,
  adoption_start date,
  adoption_end date,
  contribution_amount numeric,
  payment_method text,
  is_anonymous boolean,
  receipt_number text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  start_on date := current_date;
  end_on date;
  receipt_ref text;
begin
  if char_length(btrim(p_adopter_name)) not between 2 and 80 then
    return query select false, 'Enter a name between 2 and 80 characters'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if char_length(btrim(p_plaque_message)) not between 2 and 160 then
    return query select false, 'Enter a plaque message between 2 and 160 characters'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if not (
    (p_duration_unit = 'month' and p_duration_count between 1 and 120)
    or (p_duration_unit = 'year' and p_duration_count between 1 and 10)
  ) then
    return query select false, 'Choose a term of up to 120 months or 10 years'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if p_contribution_amount < 3500 or p_contribution_amount > 999999.99 then
    return query select false, 'Contribution must be at least $3,500'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if p_payment_method not in ('card', 'bank', 'zelle', 'check', 'stock', 'daf') then
    return query select false, 'Choose a supported payment method'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  perform 1 from public.benches where benches.id = p_bench_id for update;
  if not found then
    return query select false, 'Bench not found'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if exists (
    select 1
    from public.bench_adoptions
    where bench_adoptions.bench_id = p_bench_id
      and current_date between bench_adoptions.adoption_start and bench_adoptions.adoption_end
  ) then
    return query select false, 'This bench is already adopted'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  if not exists (
    select 1
    from public.bench_adoption_holds
    where bench_adoption_holds.bench_id = p_bench_id
      and bench_adoption_holds.session_token = p_session_token
      and bench_adoption_holds.expires_at > now()
    for update
  ) then
    return query select false, 'Your hold expired. Try again'::text,
      null::date, null::date, null::numeric, null::text, null::boolean, null::text;
    return;
  end if;

  end_on := case p_duration_unit
    when 'month' then (start_on + make_interval(months => p_duration_count))::date
    when 'year' then (start_on + make_interval(years => p_duration_count))::date
  end;
  receipt_ref := 'VCP-' || to_char(current_date, 'YYYY') || '-' ||
    upper(substr(replace(extensions.gen_random_uuid()::text, '-', ''), 1, 8));

  insert into public.bench_adoptions (
    bench_id,
    adopter_name,
    plaque_message,
    adoption_start,
    adoption_end,
    duration_count,
    duration_unit,
    contribution_amount,
    payment_method,
    is_anonymous,
    receipt_number
  ) values (
    p_bench_id,
    btrim(p_adopter_name),
    btrim(p_plaque_message),
    start_on,
    end_on,
    p_duration_count,
    p_duration_unit,
    p_contribution_amount,
    p_payment_method,
    p_is_anonymous,
    receipt_ref
  );

  delete from public.bench_adoption_holds
  where bench_adoption_holds.bench_id = p_bench_id
    and bench_adoption_holds.session_token = p_session_token;

  return query select true, 'Bench adopted'::text, start_on, end_on,
    p_contribution_amount, p_payment_method, p_is_anonymous, receipt_ref;
end;
$$;

revoke all on function public.notify_bench_adoption() from public;
revoke all on function public.adopt_bench(text, uuid, text, text, integer, text, numeric, text, boolean) from public;
grant execute on function public.adopt_bench(text, uuid, text, text, integer, text, numeric, text, boolean) to anon, authenticated;

alter publication supabase_realtime drop table public.bench_adoptions;
alter publication supabase_realtime add table public.bench_updates;
